name: Run flybirds test

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  linux:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        $CONDA/bin/conda env create --file environment.yml --name py3.8
        playwright install

    - name: Create binary
      run: |
        $CONDA/envs/py3.8/bin/flybirds run -P features/test/web

  macos:
    runs-on: macos-10.15
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        sudo $CONDA/bin/conda env create --file environment.yml --name py3.8
        playwright install

    - name: Create macos app
      run: |
        $CONDA/envs/py3.8/bin/flybirds run -P features/test/web


  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Create environment and install dependencies
      run: |
        %CONDA%\Scripts\conda.exe env create ^
        --file environment.yml --name py3.8
        playwright install

      shell: cmd

    - name: Create binary
      run: |
        %CONDA%\envs\py3.8\Scripts\flybirds run -P .\features\test\web
      shell: cmd
