name: Run flybirds test

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  linux:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: |
          pip install  flybirds
          playwright install
    - name: run demo
      run: |
        flybirds run -P features/test/web
  macos:
    runs-on: macos-10.15
    timeout-minutes: 10

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: |
          pip install  flybirds
          playwright install
    - name: run demo
      run: |
        flybirds run -P features/test/web
  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: |
          pip install  flybirds
          playwright install
    - name: run demo
      run: |
        flybirds run -P features/test/web

